### ISSUE TITLE
Заполнение README.md

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2020-11-spreadsheet#4]
Необходимо заполнить `README.md` — дать нормальное имя проекту, краткое описание и список участников с никами.

* [x] Нужно вместо **upt2020-11-spreadsheet** придумать и написать нормальное название.
* [x] Добавить краткое описание — один-два предложения.
* [x] Написать список участников со ссылками на профили.

**Comment by Flygrounder** [comment]
Было решено в #9

**Comment by Mazdaywik** [comment]
Кстати, в новой версии GitHub’а можно связывать pull request’ы с issues. На странице pull request’а есть справа поле «Linked issues». Если туда добавить issue, оно закроется автоматически при слиянии pull request’а. Я сам об этом раньше не знал — его только недавно добавили.

**Comment by Flygrounder** [comment]
> Кстати, в новой версии GitHub’а можно связывать pull request’ы с issues. На странице pull request’а есть справа поле «Linked issues». Если туда добавить issue, оно закроется автоматически при слиянии pull request’а. Я сам об этом раньше не знал — его только недавно добавили.

Будем использовать, спасибо
