### ISSUE TITLE
Ужасная расширяемость при изменений полей Cell

### ISSUE THREAD

**Issue by ZhukDima** [bmstu-iu9/utp2020-11-spreadsheet#64]
Сейчас у Cell есть три поля, которые сохраняются: type, value, color. Сейчас если нужно добавлять новые поля - например, у формулы - сохранить вычисленное значение нужно вписать это новое поле в порядка 5-7 файлов. В скором временем понадобится сохранять шрифты, размер и другие настройки не только форматирования текста, но и много другое. Надо придумать более лаконичное решение проблемы (+ нужно менять файлы, которые не то что разные люди писали, но и мне не понятно что делающие)

**Comment by MKondakova** [comment]
Пример файлов можно?

**Comment by ZhukDima** [comment]
В пул-реквесте от Лёши

**Comment by ZhukDima** [comment]
Ну может файлов и 4 - но всё же, как-то не по христиански

**Comment by MKondakova** [comment]
у Леши много пул-реквестов

**Comment by ZhukDima** [comment]
Да, который сейчас висит

**Comment by Flygrounder** [comment]
По-хорошему, если меняется что-то в клетке, то менять надо клетку и сериализатор (возможно десериализатор). Мне не кажется, что это "ужасная" расширяемость. По-крайней мере непонятно, как иначе т. к. необходимость сериализовать книги есть
